<?php

declare(strict_types=1);

namespace Ownage\Approvedeny\Exceptions;

use Throwable;

/**
 * Represents all errors generated by SDK itself.
 *
 * @codeCoverageIgnore
 */
interface BaseException extends Throwable
{
}
